/*
 * This file is generated by jOOQ.
 */
package org.jooq.example.r2dbc.db.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.example.r2dbc.db.Keys;
import org.jooq.example.r2dbc.db.TestSchema;
import org.jooq.example.r2dbc.db.tables.records.EntityRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Entity extends TableImpl<EntityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>test_schema.entity</code>
     */
    public static final Entity ENTITY = new Entity();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EntityRecord> getRecordType() {
        return EntityRecord.class;
    }

    /**
     * The column <code>test_schema.entity.id</code>.
     */
    public final TableField<EntityRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>test_schema.entity.deleted_tinyint</code>.
     */
    public final TableField<EntityRecord, Byte> DELETED_TINYINT = createField(DSL.name("deleted_tinyint"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>test_schema.entity.deleted_bit</code>.
     */
    public final TableField<EntityRecord, Boolean> DELETED_BIT = createField(DSL.name("deleted_bit"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.inline("b'0'", SQLDataType.BOOLEAN)), this, "");

    private Entity(Name alias, Table<EntityRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Entity(Name alias, Table<EntityRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>test_schema.entity</code> table reference
     */
    public Entity(String alias) {
        this(DSL.name(alias), ENTITY);
    }

    /**
     * Create an aliased <code>test_schema.entity</code> table reference
     */
    public Entity(Name alias) {
        this(alias, ENTITY);
    }

    /**
     * Create a <code>test_schema.entity</code> table reference
     */
    public Entity() {
        this(DSL.name("entity"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : TestSchema.TEST_SCHEMA;
    }

    @Override
    public Identity<EntityRecord, Integer> getIdentity() {
        return (Identity<EntityRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<EntityRecord> getPrimaryKey() {
        return Keys.KEY_ENTITY_PRIMARY;
    }

    @Override
    public Entity as(String alias) {
        return new Entity(DSL.name(alias), this);
    }

    @Override
    public Entity as(Name alias) {
        return new Entity(alias, this);
    }

    @Override
    public Entity as(Table<?> alias) {
        return new Entity(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Entity rename(String name) {
        return new Entity(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Entity rename(Name name) {
        return new Entity(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Entity rename(Table<?> name) {
        return new Entity(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Entity where(Condition condition) {
        return new Entity(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Entity where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Entity where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Entity where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Entity where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Entity where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Entity where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Entity where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Entity whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Entity whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
