services:
  test-db:
    container_name: test-db
    image: mysql:8.4.0
    ports:
      # to avoid conflicts with other databases
      - "3310:3306"
    environment:
      - MYSQL_DATABASE=test_schema
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql