/*
 * This file is generated by jOOQ.
 */
package org.jooq.example.r2dbc.db;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.example.r2dbc.db.tables.Entity;
import org.jooq.example.r2dbc.db.tables.records.EntityRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * test_schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<EntityRecord> KEY_ENTITY_PRIMARY = Internal.createUniqueKey(Entity.ENTITY, DSL.name("KEY_entity_PRIMARY"), new TableField[] { Entity.ENTITY.ID }, true);
}
