/*
 * This file is generated by jOOQ.
 */
package org.jooq.example.r2dbc.db;


import org.jooq.example.r2dbc.db.tables.Author;


/**
 * Convenience access to all tables in test_schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>test_schema.author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;
}
