/*
 * This file is generated by jOOQ.
 */
package org.jooq.example.r2dbc.db;


import org.jooq.example.r2dbc.db.tables.Entity;


/**
 * Convenience access to all tables in test_schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>test_schema.entity</code>.
     */
    public static final Entity ENTITY = Entity.ENTITY;
}
