/*
 * This file is generated by jOOQ.
 */
package org.jooq.example.r2dbc.db;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.example.r2dbc.db.tables.Entity;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TestSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>test_schema</code>
     */
    public static final TestSchema TEST_SCHEMA = new TestSchema();

    /**
     * The table <code>test_schema.entity</code>.
     */
    public final Entity ENTITY = Entity.ENTITY;

    /**
     * No further instances allowed
     */
    private TestSchema() {
        super("test_schema", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Entity.ENTITY
        );
    }
}
