/*
 * This file is generated by jOOQ.
 */
package org.jooq.example.r2dbc.db.tables.records;


import org.jooq.Record1;
import org.jooq.example.r2dbc.db.tables.Author;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AuthorRecord extends UpdatableRecordImpl<AuthorRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>test_schema.author.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>test_schema.author.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>test_schema.author.deleted</code>.
     */
    public void setDeleted(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>test_schema.author.deleted</code>.
     */
    public Byte getDeleted() {
        return (Byte) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthorRecord
     */
    public AuthorRecord() {
        super(Author.AUTHOR);
    }

    /**
     * Create a detached, initialised AuthorRecord
     */
    public AuthorRecord(Integer id, Byte deleted) {
        super(Author.AUTHOR);

        setId(id);
        setDeleted(deleted);
        resetChangedOnNotNull();
    }
}
